/*
                   Inroads Shopping Cart - Template Field Lists

                        Written 2008-2018 by Randall Severy
                         Copyright 2008-2018 Inroads, LLC
*/

insert_lists['customer'] = [['id','ID'],
                            ['email','E-Mail Address'],
                            ['encoded_email','E-Mail Address (encoded)'],
                            ['password','Password (encrypted)'],
                            ['encoded_password','Password (encoded)'],
                            ['crc_password','Password (CRC)'],
                            ['fname','First Name'],
                            ['mname','Middle Name'],
                            ['lname','Last Name'],
                            ['company','Company Name'],
                            ['create_date','Date Created'],
                            ['ip_address','IP Address'],
                            ['status','Status'],
                            ['mailing','Mailing List Flag'],
                            ['reminders','Reminders Flag'],
                            ['account','Account Name'],
                            ['sales_rep','Sales Rep']
];
insert_lists['billing'] = [['id','ID'],
                           ['parent','Parent ID'],
                           ['address1','Address Line 1'],
                           ['address2','Address Line 2'],
                           ['city','City'],
                           ['state','State'],
                           ['zipcode','Zip Code'],
                           ['country','Country Name'],
                           ['phone','Telephone #'],
                           ['fax','Fax #'],
                           ['mobile','Cell Phone #']
];
insert_lists['shipping'] = [['id','ID'],
                            ['parent','Parent ID'],
                            ['profilename','Profile Name'],
                            ['shipto','Ship To'],
                            ['company','Company Name'],
                            ['address1','Address Line 1'],
                            ['address2','Address Line 2'],
                            ['city','City'],
                            ['state','State'],
                            ['zipcode','Zip Code'],
                            ['country','Country Name'],
                            ['address_type','Address Type'],
                            ['default_flag','Default Flag']
];
insert_lists['order'] = [['id','Order/Quote/Invoice/Sales Order ID'],
                         ['customer_id','Customer ID'],
                         ['account_id','Account ID'],
                         ['account_name','Account Name'],
                         ['email','Customer E-Mail Address'],
                         ['fname','Customer First Name'],
                         ['mname','Customer Middle Name'],
                         ['lname','Customer Last Name'],
                         ['company','Company Name'],
                         ['order_number','Order Number'],
                         ['quote_id','Linked Quote ID'],
                         ['order_id','Linked Order/Sales Order ID'],
                         ['reorder_id','Reorder ID'],
                         ['currency','Currency'],
                         ['status','Status'],
                         ['order_date','Order Date'],
                         ['quote_date','Quote Date'],
                         ['invoice_date','Invoice Date'],
                         ['short_order_date','Short Order Date (mm/dd/yyyy)'],
                         ['short_quote_date','Short Quote Date (mm/dd/yyyy)'],
                         ['short_invoice_date','Short Invoice Date (mm/dd/yyyy)'],
                         ['updated_date','Updated Date'],
                         ['shipped_date','Shipped Date'],
                         ['short_shipped_date','Short Shipped Date (mm/dd/yyyy)'],
                         ['subtotal','Sub-Total'],
                         ['tax','Tax'],
                         ['shipping','Shipping Amount'],
                         ['coupon_id','Coupon ID'],
                         ['coupon_code','Coupon Code'],
                         ['coupon_amount','Coupon Amount'],
                         ['fee_name','Fee Name'],
                         ['fee_amount','Fee Amount'],
                         ['discount_name','Discount Name'],
                         ['discount_amount','Discount Amount'],
                         ['balance_due','Balance Due'],
                         ['total','Total Amount'],
                         ['tracking','Tracking Numbers'],
                         ['trackinglink','Tracking Link'],
                         ['payment_method','Payment Method'],
                         ['payment_type','Payment Type'],
                         ['card_type','Card Type'],
                         ['card_name','Name on Card'],
                         ['card_number','Card Number'],
                         ['card_month','Card Month'],
                         ['card_year','Card Year'],
                         ['card_cvv','Card CVV2'],
                         ['purchase_order','Purchase Order'],
                         ['shipping_carrier','Shipping Carrier'],
                         ['shipping_method','Shipping Method'],
                         ['payment_id','Payment ID'],
                         ['payment_code','Payment Code'],
                         ['payment_ref','Payment Ref'],
                         ['comments','Comments'],
                         ['notes','Notes'],
                         ['terms','Terms'],
                         ['partial_ship','Partial Shipment'],
                         ['downloads','# of Order Item Downloads'],
                         ['items_text','Order Items (Text)'],
                         ['items_html','Order Items (HTML)'],
                         ['items_html_with_mpn','Order Items with MPNs (HTML)'],
                         ['items','Order Items (ForEach Loop Only)'],
                         ['item_product_id','Order Item Product ID'],
                         ['item_product_url','Order Item Product URL'],
                         ['item_product_image','Order Item Product Image'],
                         ['item_product_name','Order Item Product Name'],
                         ['item_product_name_only','Order Item Product Name Only'],
                         ['item_attributes','Order Item Attributes'],
                         ['item_part_number','Order Item Part Number'],
                         ['item_price','Order Item Price'],
                         ['item_qty','Order Item Quantity'],
                         ['item_total','Order Item Total'],
                         ['item_download_url','Order Item Download URL']
];
insert_lists['product'] = [['id','ID'],
                           ['status','Status'],
                           ['name','Name'],
                           ['display_name','Display Name'],
                           ['display_price','Display Price'],
                           ['flags','Flags'],
                           ['short_description','Short Description'],
                           ['long_description','Long Description'],
                           ['seo_title','Meta Title'],
                           ['seo_description','Meta Description'],
                           ['seo_keywords','Meta Keywords'],
                           ['seo_footer','Page Footer'],
                           ['seo_url','URL Alias'],
                           ['image','Primary Image'],
                           ['url','Product URL']
];
insert_lists['inventory'] = [['id','ID'],
                            ['sequence','Sequence'],
                            ['attributes','Attributes'],
                            ['part_number','Part Number'],
                            ['qty','Quantity'],
                            ['min_qty','Minimum Quantity'],
                            ['weight','Weight'],
                            ['list_price','List Price'],
                            ['price','Regular Price'],
                            ['sale_price','Sale Price'],
                            ['cost','Cost'],
                            ['origin_zip','Origin Zip']
];
insert_lists['config'] = [['admin_email','Admin E-Mail Address'],
                          ['domain_name','Domain Name'],
                          ['website_id','Web Site ID'],
                          ['website_name','Web Site Name'],
                          ['website_hostname','Web Site Hostname'],
                          ['company_name','Config Company Name'],
                          ['base_url','Base URL'],
                          ['ssl_url','SSL URL'],
                          ['map_company','Contact Company Name'],
                          ['map_address1','Contact Address'],
                          ['map_address2','Contact Address2'],
                          ['map_city','Contact City'],
                          ['map_state','Contact State'],
                          ['map_zip','Contact Zip'],
                          ['map_country','Contact Country'],
                          ['map_phone','Contact Phone'],
                          ['map_fax','Contact Fax'],
                          ['date_time','Date/Time (m/d/Y h:i A)'],
                          ['date:[format]','Date (PHP format)'],
                          ['date_month','Date - Month (m)'],
                          ['date_day','Date - Day (d)'],
                          ['date_year','Date - Year (Y)'],
                          ['date_hours','Date - Hours (h)'],
                          ['date_minutes','Date - Minutes (i)'],
                          ['date_am_pm','Date - AM/PM (A)']
];
insert_lists['cartconfig'] = [['orderprefix','Order Number Prefix'],
                              ['contactemail','Contact Email'],
                              ['contactphone','Contact Phone'],
                              ['contacthours','Contact Hours'],
                              ['companyname','Company Name'],
                              ['companylogo','Company Logo']
];
insert_lists['ticket'] = [['id','Ticket ID'],
                          ['type','Ticket Type'],
                          ['status','Status'],
                          ['dirty','Dirty'],
                          ['department','Department'],
                          ['priority','Priority'],
                          ['cc','CC Addresses'],
                          ['title','Ticket Title'],
                          ['approved','Approved'],
                          ['url','URL'],
                          ['description','Description'],
                          ['history','History'],
                          ['comments','Comments'],
                          ['submitted','Submitted Date'],
                          ['submitter','Submitter'],
                          ['submitteremail','Submitter E-Mail'],
                          ['assigned','Assigned Date'],
                          ['assignedto','Assigned To'],
                          ['assignedtoemail','Assigned To E-Mail'],
                          ['verified','Verified Date'],
                          ['verifier','Verified By'],
                          ['date','Current Date'],
                          ['viewurl','View Ticket URL']
];
insert_lists['sage'] = [['error','Error Message'],
                        ['error_details','Error Details'],
                        ['cleanup_results','Cleanup Results']
];
insert_lists['rma'] = [['id','ID'],
                       ['status','Status'],
                       ['request_date','Request Date'],
                       ['completed_date','Completed Date'],
                       ['order_id','Order ID'],
                       ['order_number','Order Number'],
                       ['request_type','Request Type'],
                       ['opened','Package Opened'],
                       ['reason','Reason'],
                       ['reason_details','Reason Details'],
                       ['vendor','Vendor'],
                       ['vendor_rma','Vendor RMA #'],
                       ['return_address','Return Address (Text)'],
                       ['return_address_html','Return Address (HTML)'],
                       ['email','Customer E-Mail Address'],
                       ['fname','Customer First Name'],
                       ['mname','Customer Middle Name'],
                       ['lname','Customer Last Name'],
                       ['company','Company Name'],
                       ['address1','Address Line 1'],
                       ['address2','Address Line 2'],
                       ['city','City'],
                       ['state','State'],
                       ['zipcode','Zip Code'],
                       ['country','Country Code'],
                       ['phone','Telephone #'],
                       ['fax','Fax #'],
                       ['mobile','Cell Phone #'],
                       ['comments','Comments'],
                       ['notes','Notes'],
                       ['items_text','RMA Items (Text)'],
                       ['items_html','RMA Items (HTML)']
];
insert_lists['review'] = [['id','ID'],
                          ['parent','Product ID'],
                          ['status','Status'],
                          ['create_date','Created Date'],
                          ['firstname','First Name'],
                          ['lastname','Last Name'],
                          ['email','Email Address'],
                          ['subject','Subject'],
                          ['rating','Rating'],
                          ['review','Review']
];
insert_lists['vendor'] = [['id','ID'],
                          ['name','Vendor Name'],
                          ['contact','Contact Name'],
                          ['company','Company Name'],
                          ['address1','Address Line 1'],
                          ['address2','Address Line 2'],
                          ['city','City'],
                          ['state','State'],
                          ['zipcode','Zip Code'],
                          ['country','Country Code'],
                          ['phone','Telephone #'],
                          ['email','Contact E-Mail Address'],
                          ['name_on_check','Name on Check'],
                          ['account_number','Account Number'],
                          ['return_address','Return Address'],
                          ['submit_email','Order Submission E-Mail Address']
];
insert_lists['registry'] = [['id','ID'],
                            ['email','E-Mail Address'],
                            ['password','Password'],
                            ['event_name','Event Name'],
                            ['event_type','Event Type'],
                            ['event_date','Event Date'],
                            ['event_state','Event State'],
                            ['event_country','Event Country'],
                            ['event_code','Event Code'],
                            ['event_photo','Event Photo'],
                            ['event_description','Event Description'],
                            ['role','Role'],
                            ['fname','First Name'],
                            ['mname','Middle Name'],
                            ['lname','Last Name'],
                            ['company','Company'],
                            ['address1','Address Line 1'],
                            ['address2','Address Line 2'],
                            ['city','City'],
                            ['state','State'],
                            ['zipcode','Zip Code'],
                            ['country','Country Code'],
                            ['phone','Telephone #'],
                            ['co_role','Second Role'],
                            ['co_fname','Second First Name'],
                            ['co_mname','Second Middle Name'],
                            ['co_lname','Second Last Name'],
                            ['co_company','Second Company'],
                            ['co_address1','Second Address Line 1'],
                            ['co_address2','Second Address Line 2'],
                            ['co_city','Second City'],
                            ['co_state','Second State'],
                            ['co_zipcode','Second Zip Code'],
                            ['co_country','Second Country Code'],
                            ['co_phone','Second Telephone #'],
                            ['create_date','Create Date'],
                            ['ip_address','IP Address'],
                            ['status','Status'],
                            ['shipto','Ship To'],
                            ['items_text','Registry Items (Text)'],
                            ['items_html','Registry Items (HTML)']
];
insert_lists['certificate'] = [['amount','Amount'],
                               ['to','To Recipient'],
                               ['from','From Sender'],
                               ['message','Personal Message'],
                               ['email','Recipient\'s Email'],
                               ['code','Gift Certificate Code'],
                               ['certificate','Certificate Image']
];

